apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: pacemaker22/user
          env:
            - name: MONGO_URI
              value: 'mongodb://user-mongo-service:27017/user'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: ClusterIP
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
