name: deploy-manifests

on: 
  push:
    branches:
      - main
    paths: 
      - 'infra/**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save bc0420d4-cf12-4194-8a28-b03c8e156acb
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod