name: deploy-produk

on: 
  push:
    branches:
      - main
    paths: 
      - 'produk/**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd produk && docker build -t pacemaker22/produk .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push pacemaker22/produk
      - uses: digitalocean/action-doctl@v2 
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save kamaljaya
      - run: kubectl rollout restart deployment produk-depl 