name: deploy-pembayaran

on: 
  push:
    branches:
      - main
    paths: 
      - 'pembayaran/**'
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd pembayaran && docker build -t pacemaker22/pembayaran .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push pacemaker22/pembayaran
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save kamal-jaya
      - run: kubectl rollout restart deployment pembayaran-depl 
