name: tests-produk

on:
  pull_request:
    paths:
      - "produk/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd produk && npm install && npm run test:ci