name: tests-pembayaran

on:
  pull_request:
    paths:
      - "pembayaran/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd pembayaran && npm install && npm run test:ci